name: Deploy Core Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        env:
            VITE_DEV_BACKEND_URL: ${{ secrets.VITE_DEV_BACKEND_URL }}
            VITE_PROD_BACKEND_URL: ${{ secrets.VITE_PROD_BACKEND_URL }}
            VITE_PRODUCTION: ${{ secrets.VITE_PRODUCTION }}
        run: npm run build

      - name: Run Backend Smoke Test
        run: |
          chmod +x smoke-test.sh
          ./smoke-test.sh

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist/*"
          target: "/var/www/html/core-frontend"
          strip_components: 1
          rm: true

      - name: Fix Permissions & Health Check
        run: |
          # Give Nginx access to READ, but let UBUNTU keep ownership so we can delete next time
          sudo chmod -R 755 /var/www/html/core-frontend
          sudo chown -R ubuntu:www-data /var/www/html/core-frontend